//#define IDOK	                 		300
//#define IDCANCEL                 		301
#define IDC_VIEW_LOG                    3334
#define IDC_DELETE_LOG                  3335
#define IDC_LOGFILE_LIMITS				3336
#define IDC_LOGFILE_LIMIT 				3337
#define IDC_LOGFILE_TRUNCATE 			3338
#define IDC_LOGFILE_DEBUGMODE 			3339
#define IDD_ABOUT                       100
#define IDD_CONFIG                      102
#define IDC_DRAG                        205
#define IDC_HSCROLL                     206
#define IDC_CLOSE                       207
#define IDC_DEFAULT_ARROW               208
#define IDC_VSCROLL                     209
#define IDC_RESIZE                      210
#define IDC_NEWS_FRAME                  1001
#define IDC_USERNAME                    1003
#define IDC_PASSWORD                    1004
#define IDC_MAX_LOG_FILE_SIZE           1005
#define IDC_PROXY_USER		            1006
#define IDC_PROXY_PASSWORD              1007
#define IDC_PROXY_SERVER                1008
#define IDC_WEB                         1009
#define IDC_PROXY_PORT                  1010
#define IDC_UPDATE_MESSAGE              1011
#define IDC_MESSAGE1                    1012
#define IDC_MESSGE2                     1013
#define IDC_LOCAL_CONTROL_VER           1015
#define IDC_PROGRESS                    1016
#define IDC_PASSWORD_MSG                1017
#define IDC_APPLY                       1018
#define IDC_ENABLE                      1020
#define IDC_FORCE_CONNECT               1021
#define IDC_SHOW_MESSAGES               1022
#define IDC_SHOW_UPGRADE_INFO           1022
#define IDC_IGNORE_HTTP                 1023
#define IDC_SHOW_E                      1023
#define IDC_SHOW_ERRORS                 1023
#define IDC_SHOW_IMP_MSGS               1024
#define IDC_CACHE_STATS                 3000
#define IDC_VERSION                     3001
#define IDC_SERVER_STATS                3002
#define IDC_PROXY_ENABLE                3005
#define IDC_PROXY_AUTH		            3006
#define IDC_WEB_BROWSER                 3007
#define IDC_WEBBROWSER                  3008
#define IDC_COPYRIGHT                   3009
#define IDC_PROXY_SERVER_FRAME          3010
#define IDC_PROXY_AUTH_FRAME            3011
#define IDD_INC_EXC_DIRS                3012
#define IDC_LIST                        3012
#define IDC_REMOVE_ALL                  3013
#define IDC_REMOVE                      3014
#define IDC_ADD                         3015
#define IDC_NEW_DIR                     3016
#define IDC_BROWSE                      3017
#define IDC_INCLUDE_EXCLUDE             3021
#define IDC_RADIO3                      3022
#define IDC_EXCLUSIONS                  3023
#define IDC_CLEAR_PASS                  3024
